Cleanup script to use cmd line params

diff --git a/finishPi b/finishPi
--- a/finishPi
+++ b/finishPi
@@ -2,17 +2,25 @@
 
 usage () {
    NEW=$'\n'
-   u="Usage:  finishPi -e [1|2|3]${NEW}"
-   u="$u          -e (--end [1: NEMA1; 2: NEMA2; 3:Bridge)${NEW}"   
+   u="Usage:  finishPi -p (--pi)  [211|212|221|222|231]${NEW}"
+   #u="$u               -e (--end) [1: NEMA1; 2: NEMA2; 3:Bridge)${NEW}"   
    echo "$u";
    exit 1;
 }
 ##### Get Command Line
 while [ "$1" != "" ]; do
     case $1 in
-        -e | --end )         shift
-                              END=$1
+        -p | --pi )           shift
+                              PI=$1
+                              [ "$PI" == "231" ] && END=3
+                              [ "$PI" == "221" ] && END=2
+                              [ "$PI" == "222" ] && END=2
+                              [ "$PI" == "211" ] && END=1
+                              [ "$PI" == "212" ] && END=1
                               ;;
+       # -e | --end )          shift
+       #                       END=$1
+       #                       ;;
         -h | --help )         usage
                               exit 1
                               ;;
@@ -22,15 +30,21 @@ while [ "$1" != "" ]; do
     shift
 done
 ##### Check for specified end and UID on I2C
-[ -z "$END" ] && usage && exit 1
-[ "$END" == "1" ] || [ "$END" == "2" ] || [ "$END" == "3" ] || usage
+[ -z "$PI" ] && usage && exit 1
+[ "$PI" == "211" ] || [ "$PI" == "212" ] || \ 
+     [ "$PI" == "221" ] ||[ "$PI" == "222" ] || \
+     [ "$PI" == "231" ] || usage
+
+#### Check for I2C UID chip
 i2cdetect -y 1 | grep -e '-- 55 --' >/dev/null 2>&1
 [ "$?" == 0 ] && UIDADDY='0x55'
 i2cdetect -y 1 | grep -e '-- 51 --' >/dev/null 2>&1
 [ "$?" == 0 ] && UIDADDY='0x51'
 [ -z "$UIDADDY" ] && echo "No UID found at 0x51 or 0x55" && exit 1
-[ "$END" == 3 ] && [ "$UIDADDY" != "0x55" ] && echo "End 3 must have UID at 0x55" && exit 1
-[ "$END" != 3 ] && [ "$UIDADDY" != "0x51" ] && echo "End 1 or 2 must have UID at 0x51" && exit 1
+[ "$PI" == "231" ] && [ "$UIDADDY" != "0x55" ]   && echo "Unable to find UID at 0x55" && exit 1
+[ "$PI" != "231" ] && [ "$UIDADDY" != "0x51" ]   && echo "Unable to find UID at 0x51" && exit 1
+
+#### Check for readonly FS
 READONLY=`$HOME/APC_TestTools/isreadOnly`
 
 echo  "### Refresh git"
@@ -41,47 +55,26 @@ echo  "### Stop fire"
 sudo systemctl stop fire
 
 if [ "$READONLY" == "1" ]; then
-   echo "## Mount rw to enable updates "
+   echo "### Mount rw to enable updates "
    sudo mount -o remount,rw /
    sudo mount -o remount,rw /boot
 fi
 
-if  [ $END -eq 3 ];then
-   echo "### Configure ini file"
-   sed -i 's/myRole=[^ ]*/myRole=rLog/' $HOME/RPi/config.ini
-   $HOME/updates/PiInstall/staticIP.sh 31
-   crontab $HOME/updates/PiInstall/cron3.tab
-   $HOME/APC_TestTools/setupThumbDATA
-   echo " ### Get UIDs"
-   $HOME/APC_TestTools/queryI2C.pl
-   $HOME/APC_TestTools/setPiHostname 0x55
-   sudo systemctl enable fire
-   $HOME/APC_TestTools/setupThumbLDATA
-elif [ $END -eq 1 ]  || [ $END -eq 2 ]; then
-   echo "### Configure End $end"
-   if [ grep ^myRole=Pi1 ]; then
-      [ "$END" == "1" ] && $HOME/updates/PiInstall/staticIP.sh 11
-      [ "$END" == "2" ] && $HOME/updates/PiInstall/staticIP.sh 21
-      echo "### Configure Pi1-End$END"
-      sed -i 's/myRole=[^ ]*/myRole=Pi1-End$END/' $HOME/RPi/config.ini
-      sed -i 's/I2C_sleep=[^ ]*/I2C_sleep=0.01/' $HOME/RPi/config.ini
-      crontab $HOME/updates/PiInstall/cron1.tab
-   else
-      echo "### Configure Pi2-End$END"
-      [ "$END" == "1" ] && $HOME/updates/PiInstall/staticIP.sh 12
-      [ "$END" == "2" ] && $HOME/updates/PiInstall/staticIP.sh 22
-      sed -i 's/myRole=[^ ]*/myRole=Pi2-End$END/' $HOME/RPi/config.ini
-      crontab $HOME/updates/PiInstall/cron2.tab
-   fi
-   echo " ##### Getting UIDs "
-   $HOME/APC_TestTools/getUID
-   Ard=`$HOME/APC_TestTools/I2Cio.pl read 0x0A 0x00 | cut -d' ' -f4`
-   sudo systemctl enable fire
-   echo "Arduino Version $Ard"
-   $HOME/APC_TestTools/setPiHostname 0x51
-   $HOME/APC_TestTools/moveThumbLDATA
-fi
+$HOME/updates/PiInstall/staticIP.sh $PI
+[ "$PI" == "211" ] && crontab $HOME/updates/PiInstall/cron1.tab
+[ "$PI" == "221" ] && crontab $HOME/updates/PiInstall/cron1.tab
+[ "$PI" == "212" ] && crontab $HOME/updates/PiInstall/cron2.tab
+[ "$PI" == "222" ] && crontab $HOME/updates/PiInstall/cron2.tab
+[ "$PI" == "231" ] && crontab $HOME/updates/PiInstall/cron3.tab
 
+[ "$PI" == "231" ] && $HOME/APC_TestTools/setupThumbDATA
+
+sudo systemctl enable fire
+$HOME/APC_TestTools/moveThumbLDATA
+$HOME/APC_TestTools/setPiHostname $UIDADDY
+echo ""
+$HOME/APC_TestTools/queryI2C.pl |grep -e Ard -e UID -A 1 | grep -v 1B | grep -v 68
+echo ""
 echo "Restarting in 10..."
 sleep 10
 sudo shutdown -r now
